module.exports = [{
    courseOrder: '1',
    name: 'Bryant Lake Disc Golf Course',
    location: 'Eden Prairie, Minnesota',
    zipcode: '55344',
    holes: '18',
    length: '5947',
    parInfo: '60',
    waterHoles: true,
    teeType: 'Concrete (XL)',
    cost: '6.45',
    beginnerFriendly: false,
    description: `Challenging championship course design that overlooks a scenic lake. Rolling hills with challenging elevation changes. Great variation of wooded and open holes with near-perfect groundskeeping. All tee boxes and pin locations are nice and clean. Alternate tees and pin placements. Allen's favorite overall course that is close to the Twin Cities. `,
    image1: 'https://res.cloudinary.com/amjdev/image/upload/v1642020280/bryantlake1_jncxhg.jpg',
    image2: 'https://res.cloudinary.com/amjdev/image/upload/v1642031865/c07058f9_xbjzwn.jpg',
    image3: 'https://res.cloudinary.com/amjdev/image/upload/v1642031941/e72362e7_ncrcw5.jpg',
    image4: 'https://res.cloudinary.com/amjdev/image/upload/v1642039244/blakebryant_fxagyc.jpg',
},
{
    courseOrder: '3',
    name: 'Sunnyside Park',
    location: 'New Hope, Minnesota',
    zipcode: '55428',
    holes: '9',
    length: '2413',
    parInfo: '27',
    waterHoles: true,
    teeType: 'Concrete',
    cost: '0',
    beginnerFriendly: true,
    description: 'Small nicely groomed park alongside an industrial area. Some moderate elevation with a few OB challenges (street and water).',
    image1: 'https://res.cloudinary.com/amjdev/image/upload/v1642031380/f9f76f09_wjzi0j.jpg',
    image2: 'https://res.cloudinary.com/amjdev/image/upload/v1642143051/52b98c8e_pjcbln.jpg',
    image3: 'https://res.cloudinary.com/amjdev/image/upload/v1642143119/e2e15d32_lmuudg.jpg',
    iamge4: 'https://res.cloudinary.com/amjdev/image/upload/v1642143143/b629e39f_wpcaiu.jpg',
},
{
    courseOrder: '2',
    name: 'Blue Ribbon Pines',
    location: 'East Bethel, Minnesota',
    zipcode: '55011',
    holes: '27',
    length: '9493',
    parInfo: '88',
    waterHoles: true,
    teeType: 'Concrete (XL)',
    cost: '8.00',
    beginnerFriendly: false,
    description: `Professional level course. Open and wooded with ponds, doglegs, abundant risk/reward and signature holes. 100' tall pine trees with beautiful landscaping and attention to course detail. This course tests every aspect of your game. Plan on taking an entire day to make the most out of playing this course`,
    image1: 'https://res.cloudinary.com/amjdev/image/upload/v1642032400/335166a2_x075w7.jpg',
    image2: 'https://res.cloudinary.com/amjdev/image/upload/v1642038993/allenbrphole4_jpksak.jpg',
    image3: 'https://res.cloudinary.com/amjdev/image/upload/v1642032590/IMG_1712-510x382_hq1v3i.jpg',
    image4: 'https://res.cloudinary.com/amjdev/image/upload/v1642032635/blue-ribbon-pines-water.jpg',
},
{
    courseOrder: '4',
    name: 'Basset Creek Park',
    location: 'Crystal, Minnesota',
    zipcode: '55428',
    holes: '15',
    length: '4345',
    parInfo: '46',
    waterHoles: false,
    teeType: 'Asphalt',
    cost: '0',
    beginnerFriendly: true,
    description: `Course that loops around Basset Creek Park that is situated in a suburban neighborhood. Variety of open field holes and holes with tree obstacles. In 2015 3 holes were added that go back into the woods for more variety. Two fun holes for ace runs from the top of a large hill. All skill levels from beginner to pro will find this course enjoyable.`,
    image1: 'https://res.cloudinary.com/amjdev/image/upload/v1642142841/1b2fa1cf_aicsa1.jpg',
    image2: 'https://res.cloudinary.com/amjdev/image/upload/v1642142390/3f9d5644e75b0f16549a84b03748e2ba_m_f4NnLZSHCan9h81cTrIC40OpfFKN_snojly.jpg',
    image3: 'https://res.cloudinary.com/amjdev/image/upload/v1642142356/09b4b6fe560ab8aa42f2abc5bd21477a_m_qNZYJ4IGoG59qwPAYHUzkg11I2Dv_gf4td0.jpg',
    image4: 'https://res.cloudinary.com/amjdev/image/upload/v1642142562/cd0497aa7a9cba726ed5597fd57d5bf0_m_DipUu7obmi29YVaK8sKicZN41nhO_d4s0cg.jpg',
},
{
    courseOrder: '5',
    name: 'The Valley Disc Golf Course',
    location: 'Inver Grove Heights, Minnesota',
    zipcode: '55076',
    holes: '18',
    length: '6875',
    parInfo: '60',
    waterHoles: true,
    teeType: 'Poured Concrete',
    cost: '5.00',
    beginnerFriendly: false,
    description: `Plays on the hillsides of a bowl-shaped valley with scenic views of many holes from several vantage points. Particularly unique hole #3 that is a tight dogleg to the right with all the trees bending to the right as well! There is also one challenging pond crossing that is not for the faint of heart or weak of arm.`,
    image1: 'https://res.cloudinary.com/amjdev/image/upload/v1642144160/5a256958_rqoznk.jpg',
    image2: 'https://res.cloudinary.com/amjdev/image/upload/v1642143903/thevalley2_plpkhd.jpg',
    image3: 'https://res.cloudinary.com/amjdev/image/upload/v1642143949/thevalley3_pbwuno.jpg',
    image4: 'https://res.cloudinary.com/amjdev/image/upload/v1642143826/thevalley1_worgh4.jpg',
},
];