module.exports = [{
    name: 'Bryant Lake Disc Golf Course',
    location: 'Eden Prairie, Minnesota',
    zipcode: '55344',
    holes: '18',
    length: '5947',
    parInfo: '60',
    waterHoles: true,
    teeType: 'Concrete (XL)',
    cost: '6.45',
    beginnerFriendly: false,
    description: 'Challenging championship design overlooking scenic lake. Rolling hills with elevation changes. Tee boxes and pin locations manicured immaculately. Alt. tees and pin placements. Many park amenities including concessions/pro shop.',
    image1: 'https://res.cloudinary.com/amjdev/image/upload/v1642020280/bryantlake1_jncxhg.jpg',
    image2: 'https://res.cloudinary.com/amjdev/image/upload/v1642031865/c07058f9_xbjzwn.jpg',
    image3: 'https://res.cloudinary.com/amjdev/image/upload/v1642031941/e72362e7_ncrcw5.jpg',
    image4: 'https://res.cloudinary.com/amjdev/image/upload/v1642031986/a0f63129_ug3pno.jpg',
},
{
    name: 'Sunnyside Park',
    location: 'New Hope, Minnesota',
    zipcode: '55428',
    holes: '9',
    length: '2413',
    parInfo: '27',
    waterHoles: true,
    teeType: 'Concrete',
    cost: '0',
    beginnerFriendly: true,
    description: 'Small nicely groomed park alongside an industrial area. Some moderate elevation with a few OB challenges (street and water).',
    image1: 'https://res.cloudinary.com/amjdev/image/upload/v1642031380/f9f76f09_wjzi0j.jpg',
},
{
    name: 'Blue Ribbon Pines',
    location: 'East Bethel, Minnesota',
    zipcode: '55011',
    holes: '27',
    length: '9493',
    parInfo: '88',
    waterHoles: true,
    teeType: 'Concrete (XL)',
    cost: '8.00',
    beginnerFriendly: false,
    description: `Professional level course. Open and wooded with ponds, doglegs, abundant risk/reward and signature holes. 100' tall pines. Tests every aspect of your game.`,
    image1: 'https://res.cloudinary.com/amjdev/image/upload/v1642032400/335166a2_x075w7.jpg',
    image2: 'https://res.cloudinary.com/amjdev/image/upload/v1642032459/a9b2db62_niiavk.jpg',
    image3: 'https://res.cloudinary.com/amjdev/image/upload/v1642032590/IMG_1712-510x382_hq1v3i.jpg',
    image4: 'https://res.cloudinary.com/amjdev/image/upload/v1642032635/blue-ribbon-pines-water.jpg',
},
];